language: minimal
services: docker
env:
  matrix:
    - DOCKER_COMPOSE_VERSION=1.23.2
  global:
    - secure: NbP2QdCa3vv3BTAG5kZHcYrNQqvmvo/XeR+DF4oN9OdSiFDFP0h+ZZm4cMDX1bp6cETA8JwzhZZbN4ysPChOmL/qpufNsDawiD8D7PS8whi7zcZb9kLzrZ3EFu00IG8xCprP1qOR9VRwOhQrWNW4odeeAUKKJ+rzDrU+bbnTvJNWKRQygdmrBsg7LmdSxx/zMnqYiS3j1PwFsTxS2xaDVd8LC06uh7iSjpzp/u2arrZcC2BTwasNJVZ0Y0c/J2D0AL/PqKLwpbxCXUg7od+gNafLUPTI8f+gRXc2fRX6d318qF7LODUCpdDeclbaVttYirRlLx+XK6viih0N/uuCj4e1mPUqXx6U5PEg2c/DuSrbNlcyD44wbnfeq62tueClSzvqjI5cFrmnwL2OZxePjVPJkDOUSrFr71voDkq+L0Vjf11SY6XgRspX2WiA2odvFNWOvE3PTMQS2err3SOMoMXF6rr87LPdm6aNN98vusYJYrYKJPKMlAxnznpkcXWwK1F9tVXgApR3M0tqYIYTlVqxuekY7NaTGi6DblPpv58B3IR0BV18azojQuB1gRnjG54xiP17qOkSQ+RVbStVtaILe4g9S4rb8qtCmzfPJoMzR4Wc/ASAcZweHEVczGaJXqi850qXIa9dAPZd0j3aIp4hb0pZp9/vIUmRkc87QF8=
    - secure: VHdFi+8FO3MubQUiLCy0R3s0czP0NEzxtOvkZ5yf03cvwY/AgB039EbaI1q8zTIjiLThbIpr+/Nv7khPGFKFe2zoEzZPakW+EnRTJrese4l65dQf3NcMNHJGME8jmpwUpNnQXapdGCNeVuEGZ9PQ7uT6/Yqx1K540wjR3nyvqEGzua6Ii9VHGvrZjg3gL7Tff/jNmVgdbzqjSPm/aATjoVewbPe3ZYaD33vwIilsu3J94ALJK4yHnPONL8JzURRqh26Q6objUNYqd43pe1gPqGI52rgRCbX1EgmYwvHCFaAs75IHUpCgkU7/S48yQg1joOEpcqe1B95KTjiwAltlGvVnCC9mTXlEQzLfiBeE09YETVOquYj277jVn61CShiX7/jtEu8lCW3Y+gkj/Dz3E81dPpcDaYCKb+/JCkbSmALCeuig/mGyKD2dymfodFFBLuop3LYxD4pAODTqKdy+OROpDTGrMUmys2ETundgeF0uUvA7+Y/D7b5CnMOn7QGSmsKJF1zpFsLyKdFzlNuSvU9oXiV9EUx0Ri3rVgkcJnFWVD+k//qS+2GAes8tzBnJeKk6+fUp5lfL9l4e6VW7pDTwuaetbd+SYOmTZ76z4LwVG0TLA9ZCLrN9f5Z64QIivkYAXego9nJc1Su0unfbYkVeFmjjKixzhGv0sDnR+V8=
    - secure: jVlJ9WDb+NhjM92IsGtbyxz0aLVN8O8f8cBSViSJiqW8W8ct9A018ua7/ckTjjaVQ2Z82YH2FcmhrQ38DiLyK2MqgzP0k26QU3imhS8YhExoM9XUv81f5weZT2P9tefjWizLvV0Uopjdy0hh943RNWqzkFtttbIFod7nnMH/RmbqIjpj9Qs1OIRCEbAc9m8eCu8bE/orCphkVA9nto8cq4G/uJHPP1V3MtfH6Kg4iFyfrgn5FEwiuMdSFyMcjajd+pjrEnfX6vQYbtuZ88fC2pZiA3v5kMydDZUO5kipFYoRPkUAQedoZHbhhfpnrU+s+K7hgSs/74SZyroHbsEUbTQavvsgRG8P56vFN2yLiztMGVJ/WKnue7kwGoG1Pyg182wPSDf+tLzuQzupij7zwMeClmxor4gjpIXsZHKCd2eVBlpNhcsdKzm+jqtxBIJgY9ybzlhZEQdX4aBHLIJHYC991L0h2pC5M2+Y+QWKEwxoYA/YHTYV6x/wrZElJus+0YPmvoauLBnZ3AGS2QmaI1klwqQNni7q+nHJ3xk4L4JP6B17Px96VoA/1vg8Vzphs/sixltUT65XZ/POrjJCLKxzfP8C5nqzhFstSxy7vR0FABfSYotSRGQps+ciEgeGiWrzYIzmxqgxOY6H2L8cDrK3LAMTzUFDlsgXqsl+CTs=
before_install:
  - docker -v && docker-compose -v
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
    -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - mkdir ${HOME}/.kube
  - cp udacity-c3-deployment/k8s/udagram-kubeconfig ${HOME}/.kube/config
install:
  - echo 'Hello Udacity..3.'
  - docker-compose -f udacity-c3-deployment/docker/docker-compose-build.yaml build --parallel
  - docker push bytenaija/udacity-restapi-feed
  - docker push bytenaija/udacity-restapi-user
  - docker push bytenaija/reverseproxy
  - docker push bytenaija/udacity-frontend:local
  - kubectl apply -f udacity-c3-deployment/k8s/backend-feed-service.yaml
  - kubectl apply -f udacity-c3-deployment/k8s/backend-user-service.yaml
  - kubectl apply -f udacity-c3-deployment/k8s/frontend-service.yaml
  - kubectl apply -f udacity-c3-deployment/k8s/reverseproxy-service.yaml
  - kubectl apply -f udacity-c3-deployment/k8s/aws-secret.yaml
  - kubectl apply -f udacity-c3-deployment/k8s/env-configmap.yaml
  - kubectl apply -f udacity-c3-deployment/k8s/env-secret.yaml
  - kubectl apply -f udacity-c3-deployment/k8s/backend-feed-deployment.yaml
  - kubectl apply -f udacity-c3-deployment/k8s/backend-user-deployment.yaml
  - kubectl apply -f udacity-c3-deployment/k8s/frontend-deployment.yaml
  - kubectl apply -f udacity-c3-deployment/k8s/reverseproxy-deployment.yaml
